spring.application.name=kafka-stream-study

server.port=8080

app.kafka.topics.orders-input=orders-input
app.kafka.topics.alerts-output=alerts-output
app.kafka.topics.purchase-input=purchase-input
app.kafka.topics.reward-accumulator-output=reward-accumulator-output
app.kafka.order-value-threshold=100.0

#added for clear test results
app.kafka.topic-management.delete-on-shutdown=true

app.kafka.topic-management.partitions=1
app.kafka.topic-management.replication-factor=1

spring.kafka.bootstrap-servers=localhost:9093

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.kafkastreamstudynew.model
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.group-id=kafka-stream-study-consumer
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.streams.application-id=kafka-stream-study-app
spring.kafka.streams.properties.processing.guarantee=exactly_once_v2
spring.kafka.streams.properties.num.stream.threads=1
spring.kafka.streams.properties.commit.interval.ms=1000
